const TeamMember = require("../models/TeamMember");
const fs = require("fs");
const path = require("path");

// Get all team members
exports.getTeamMembers = async (req, res) => {
  try {
    const members = await TeamMember.find().sort({ createdAt: -1 });
    res.status(200).json({ success: true, data: members });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// Create a new team member
exports.createTeamMember = async (req, res) => {
  try {
    const { name, designation, instagram, facebook, whatsapp } = req.body;

    if (!name || !designation) {
      return res.status(400).json({ success: false, message: "Name and designation are required" });
    }

    // Use the WebP URL generated by the multer/sharp middleware if a file was uploaded
    const image = req.file
      ? req.file.url
      : req.body.image || "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80";

    const newMember = await TeamMember.create({
      name,
      designation,
      instagram: instagram || "@username",
      facebook: facebook || "username",
      whatsapp: whatsapp || "+91 00000 00000",
      image,
    });

    res.status(201).json({ success: true, data: newMember });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// Update an existing team member
exports.updateTeamMember = async (req, res) => {
  try {
    const { id } = req.params;
    const { name, designation, instagram, facebook, whatsapp } = req.body;

    const existingMember = await TeamMember.findById(id);
    if (!existingMember) {
      return res.status(404).json({ success: false, message: "Team member not found" });
    }

    const updateData = {
      name: name !== undefined ? name : existingMember.name,
      designation: designation !== undefined ? designation : existingMember.designation,
      instagram: instagram !== undefined ? instagram : existingMember.instagram,
      facebook: facebook !== undefined ? facebook : existingMember.facebook,
      whatsapp: whatsapp !== undefined ? whatsapp : existingMember.whatsapp,
    };

    // If a new image file was uploaded via multer, use its generated URL
    if (req.file) {
      updateData.image = req.file.url;
      
      // Optional: Delete old local image file if it exists inside /uploads/team/
      if (existingMember.image && existingMember.image.startsWith("/uploads/")) {
        const oldImagePath = path.join(__dirname, "..", existingMember.image);
        if (fs.existsSync(oldImagePath)) {
          fs.unlinkSync(oldImagePath);
        }
      }
    }

    const member = await TeamMember.findByIdAndUpdate(id, updateData, {
      new: true,
      runValidators: true,
    });

    res.status(200).json({ success: true, data: member });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// Delete a team member
exports.deleteTeamMember = async (req, res) => {
  try {
    const { id } = req.params;
    const member = await TeamMember.findByIdAndDelete(id);

    if (!member) {
      return res.status(404).json({ success: false, message: "Team member not found" });
    }

    // Optional: Delete local image file from uploads folder if it exists
    if (member.image && member.image.startsWith("/uploads/")) {
      const imagePath = path.join(__dirname, "..", member.image);
      if (fs.existsSync(imagePath)) {
        fs.unlinkSync(imagePath);
      }
    }

    res.status(200).json({ success: true, message: "Team member deleted successfully" });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};